include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - empty_catches
    - avoid_empty_else
    - avoid_print
    - avoid_relative_library_imports
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_adjacent_string_concatenation
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - use_to_close_sinks
    - prefer_final_fields
    - use_string_buffers
    - use_setters_to_change_properties
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_overrides
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - null_closures
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_variables
    - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - package_shadowed_by_local
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_to_conditional_expressions
    - prefer_if_not_null
    - prefer_if_not_null_for_nullable_bool_conversion
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_is_operator
    - prefer_null_aware_operators
    - provide_deprecation_message
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unsafe_html
    - uri_has_not_been_literal
    - valid_regexps
    - void_checks
